name: u_flutter_y
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/sample_png.png

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Italic-VariableFont_wght.ttf
        - asset: fonts/Raleway-VariableFont_wght.ttf
          style: italic

    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
